set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-sensible"

set -g @plugin "Nybkox/tmux-kanagawa"
set -g @kanagawa-theme "wave"
set -g @kanagawa-ignore-window-colors true
set -g @kanagawa-battery-label "␥"
set -g @kanagawa-show-location false

run-shell "$HOME/dotfiles/tmux/plugins/tpm/tpm"
