set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-sensible"

set -g @plugin "Nybkox/tmux-kanagawa"
set -g @kanagawa-theme "wave"
set -g @kanagawa-ignore-window-colors true
set -g @kanagawa-battery-label "␥"

set -g @kanagawa-plugins "cpu-usage ram-usage"

set -g @kanagawa-cpu-usage-label "CPU"
set -g @kanagawa-ram-usage-label "RAM"

set -g @kanagawa-show-powerline false

set -g allow-passthrough on

# opencode
set -g @opencode_status ""

#keymaps
unbind C-b
set-option -g prefix C-`
bind-key C-` send-prefix

# Moving to left/down/up/right panes re-zooms them immediately
bind-key -r h select-pane -L -Z
bind-key -r j select-pane -D -Z
bind-key -r k select-pane -U -Z
bind-key -r l select-pane -R -Z

# opencode
bind-key o switch-client -T opencode_keys
bind-key -T opencode_keys c split-window -h -l 50% "opencode --port 8888"

set -g window-style "bg=default"
set -g window-active-style "bg=default"
set -g pane-border-style "fg=default,bg=default"
set -g pane-active-border-style "fg=magenta,bg=default"
set -g status-style "bg=default"

run-shell "$HOME/dotfiles/tmux/plugins/tpm/tpm"
